services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www  
    depends_on:
      - frontend
      - backend
  

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www
    expose:
      - 9000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    
   
   
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0 
      - PORT=3000
  

  mysql:
    image: mysql:8
    #container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}

